name: Civil Services - City Council Data for Los Angeles, CA
description: This project provides the City Council Data, Headshots & City Photo for Los Angeles, CA ( JSON, XML, CSV, SQL & YML formats )
theme: jekyll-theme-cayman